import {Router} from 'express'; import bcrypt from 'bcryptjs'; import jwt from 'jsonwebtoken'; import {z} from 'zod'; import {Admin,Announcement,Event,GalleryImage,Inquiry,Prasadam,Service,TempleTiming} from '../models/index.js'; import {requireAdmin} from '../middleware/auth.js';
const router=Router(); const models:any={services:Service,events:Event,prasadam:Prasadam,gallery:GalleryImage,timings:TempleTiming,announcements:Announcement};
const safe=(fn:any)=>(req:any,res:any,next:any)=>Promise.resolve(fn(req,res,next)).catch(next);
router.post('/auth/login',safe(async(req,res)=>{const data=z.object({email:z.string().email(),password:z.string().min(8)}).parse(req.body);const admin=await Admin.findOne({email:data.email.toLowerCase()});if(!admin||!await bcrypt.compare(data.password,admin.passwordHash))return res.status(401).json({message:'Invalid email or password'});const token=jwt.sign({id:admin.id,role:admin.role},process.env.JWT_SECRET||'',{expiresIn:'8h'});res.json({token,admin:{name:admin.name,email:admin.email,role:admin.role}})}));
router.get('/events',safe(async(req,res)=>{const q:any={published:true};if(req.query.upcoming==='true')q.date={$gte:new Date()};const data=await Event.find(q).sort({date:1}).limit(Math.min(Number(req.query.limit)||50,100));res.json({data})}));
for(const key of ['services','prasadam','gallery','timings','announcements']){router.get('/'+key,safe(async(_req,res)=>res.json({data:await models[key].find(key==='timings'?{active:true}:{}).sort({createdAt:-1})})));router.post('/'+key,requireAdmin,safe(async(req,res)=>res.status(201).json({data:await models[key].create(req.body)})));router.patch('/'+key+'/:id',requireAdmin,safe(async(req,res)=>res.json({data:await models[key].findByIdAndUpdate(req.params.id,req.body,{new:true,runValidators:true})})));router.delete('/'+key+'/:id',requireAdmin,safe(async(req,res)=>{await models[key].findByIdAndDelete(req.params.id);res.status(204).end()}))}
router.post('/events',requireAdmin,safe(async(req,res)=>res.status(201).json({data:await Event.create(req.body)})));router.patch('/events/:id',requireAdmin,safe(async(req,res)=>res.json({data:await Event.findByIdAndUpdate(req.params.id,req.body,{new:true,runValidators:true})})));router.delete('/events/:id',requireAdmin,safe(async(req,res)=>{await Event.findByIdAndDelete(req.params.id);res.status(204).end()}));
router.post('/inquiries',safe(async(req,res)=>{const data=z.object({name:z.string().trim().min(2).max(100),contact:z.string().trim().min(4).max(150),message:z.string().trim().min(5).max(3000)}).parse(req.body);await Inquiry.create(data);res.status(201).json({message:'Inquiry received'})}));router.get('/inquiries',requireAdmin,safe(async(_req,res)=>res.json({data:await Inquiry.find().sort({createdAt:-1})})));
router.get('/search',safe(async(req,res)=>{const q=String(req.query.q||'').trim();if(q.length<2)return res.json({data:[]});const regex=new RegExp(q.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),'i');const [services,events,announcements]=await Promise.all([Service.find({$or:[{title:regex},{description:regex}]}).limit(10),Event.find({$or:[{name:regex},{description:regex}]}).limit(10),Announcement.find({$or:[{title:regex},{description:regex}]}).limit(10)]);res.json({data:[...services,...events,...announcements]})}));
router.post('/chat',safe(async(req,res)=>{const {message}=z.object({message:z.string().trim().min(1).max(500)}).parse(req.body);const q=new RegExp(message.split(/\s+/).filter((w:string)=>w.length>2).join('|'),'i');const [timings,events,services]=await Promise.all([TempleTiming.find({$or:[{type:q},{description:q}],active:true}).limit(3),Event.find({$or:[{name:q},{description:q}],published:true}).sort({date:1}).limit(3),Service.find({$or:[{title:q},{description:q}],published:true}).limit(3)]);const facts=[...timings.map(x=>`${x.type}: ${x.startTime||''} ${x.endTime||''}`),...events.map(x=>`${x.name} on ${x.date.toLocaleDateString()}`),...services.map(x=>x.title)];const reply=facts.length?`Here is the published information I found: ${facts.join('; ')}.`:'I do not have published information for that yet. Please contact the temple directly once official contact details are available.';res.json({reply})}));
export default router;
