import mongoose,{Schema,model} from 'mongoose';
const opts={timestamps:true};
export const Admin=model('Admin',new Schema({name:{type:String,required:true},email:{type:String,required:true,unique:true,lowercase:true},passwordHash:{type:String,required:true},role:{type:String,enum:['admin'],default:'admin'}},opts));
export const Service=model('Service',new Schema({title:{type:String,required:true},subtitle:String,description:{type:String,required:true},imageUrl:String,timing:String,published:{type:Boolean,default:true}},opts));
export const Event=model('Event',new Schema({name:{type:String,required:true},date:{type:Date,required:true},time:String,location:String,description:{type:String,required:true},imageUrl:String,published:{type:Boolean,default:true}},opts));
export const Prasadam=model('Prasadam',new Schema({name:{type:String,required:true},description:{type:String,required:true},availability:String,timing:String,imageUrl:String,active:{type:Boolean,default:true}},opts));
export const GalleryImage=model('GalleryImage',new Schema({title:{type:String,required:true},imageUrl:{type:String,required:true},cloudinaryId:String,category:{type:String,default:'General'}},opts));
export const TempleTiming=model('TempleTiming',new Schema({type:{type:String,required:true},day:{type:String,default:'Daily'},startTime:String,endTime:String,description:String,active:{type:Boolean,default:true}},opts));
export const Announcement=model('Announcement',new Schema({title:{type:String,required:true},description:{type:String,required:true},imageUrl:String,date:{type:Date,default:Date.now},active:{type:Boolean,default:true}},opts));
export const Inquiry=model('Inquiry',new Schema({name:{type:String,required:true},contact:{type:String,required:true},message:{type:String,required:true},status:{type:String,enum:['new','read','resolved'],default:'new'}},opts));
export const Donation=model('Donation',new Schema({type:String,amount:Number,donorName:String,paymentId:String,status:{type:String,enum:['pending','paid','failed'],default:'pending'}},opts));
export const connectDb=()=>mongoose.connect(process.env.MONGODB_URI||'',{serverSelectionTimeoutMS:10000}).then(()=>console.log('MongoDB connected'));
